spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/gulimall_ums
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        service: gulimall-member
        server-addr: localhost:8848
        group: gulimall
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000


