spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: gulimall-gateway
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id : qq_route
          uri: https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme-zh.md
          predicates:
            - Query=url,qq
